apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: mariadb
spec:
  storageClassName: mariadb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: mariadb-root-secret
type: Opaque
data:
  password: YWRtaW4=

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
  clusterIP: None
  
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.4.6
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-secret
              key: password
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "mysqladmin -u root -padmin ping"
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5 
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "mysql -u root -padmin -e 'show databases'"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5 
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 3306
          name: default
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim